---
exclude: |-
  (?x)^(
    .*\/boars\.mp4|
    .*\/poster\.png|
    _extensions\/.*
  )$
repos:
  - repo: https://github.com/paddyroddy/.github
    rev: v0.353.0
    hooks:
      - id: general-hooks
      - id: lua-hooks
