---
project:
  type: website

execute:
  cache: true

format:
  html:
    include-in-header: _assets/html/goat_counter.html
    theme: darkly
  revealjs:
    auto-play-media: true
    auto-stretch: false
    callout-appearance: simple
    code-copy: true
    filters:
      - _filters/slugify.lua
    footer: "{{< meta title >}}"
    hash-type: number
    history: false
    include-after-body: _assets/html/hide_title_slide.html
    include-in-header: _assets/html/goat_counter.html
    incremental: true
    link-external-filter: ^https:\/\/paddyroddy\.github\.io
    link-external-icon: true
    logo: https://www.gravatar.com/avatar/b991f7f475c334cc277869a709445d42?s=200
    mermaid:
      theme: dark
    menu:
      hideMissingTitles: true
      useTextContentForMissingTitles: false
    mobile-view-distance: 10
    slide-number: c
    theme:
      - dark
      - _assets/css/custom.scss
    transition: fade
    view-distance: 10

website:
  favicon: _assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/talks
  site-url: https://paddyroddy.github.io/talks
  title: Patrick J. Roddy
